# Generated by Django 5.2.5 on 2025-08-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyitem',
            name='back_image',
            field=models.ImageField(blank=True, help_text='Back view of the currency item', null=True, upload_to='currency_items/back/'),
        ),
        migrations.AddField(
            model_name='currencyitem',
            name='front_image',
            field=models.ImageField(blank=True, help_text='Front view of the currency item', null=True, upload_to='currency_items/front/'),
        ),
        migrations.AlterField(
            model_name='currencyitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='currency_items/'),
        ),
    ]
